"""Semantic/layout checks for PDFs generated by dossier-pdf-tests.ts (no network)."""
from pathlib import Path
import re

import pdfplumber
from pypdf import PdfReader


output = Path(__file__).resolve().parents[2] / "output" / "pdf"
expected = {
    "contrat-medecin-exemple.pdf": (3, "Dr François Cœur", 2),
    "declaration-medecin-exemple.pdf": (2, "Déclaration de remplacement", 1),
    "contrat-etudiant-exemple.pdf": (3, "Chloé Noël", 2),
    "demande-etudiant-exemple.pdf": (2, "Demande d’autorisation", 1),
    "contrat-texte-long-qa.pdf": (6, "FIN DES MODALITÉS DE RÈGLEMENT.", 2),
}
for filename, (page_count, required, signatures) in expected.items():
    path = output / filename
    reader = PdfReader(path)
    assert len(reader.pages) == page_count, (filename, "Unexpected page count")
    texts = [page.extract_text() for page in reader.pages]
    full = "\n".join(texts)
    normalized = re.sub(r"\s+", " ", full)
    assert required in normalized, (filename, "Missing text or corrupted accents")
    assert "Dr Élodie Lefèvre" in full
    assert "\ufffd" not in full, (filename, "Replacement glyph in extracted text")
    for i, text in enumerate(texts, 1):
        assert f"{i} / {page_count}" in text, (filename, i, "Missing page number")
        assert len(text) > 100, (filename, i, "Unexpected almost empty page")
    signature_pages = [text for text in texts if "Signature manuscrite" in text]
    assert len(signature_pages) == 1
    assert signature_pages[0].count("Signature manuscrite") == signatures
    if "contrat-" in filename:
        assert "Aucune clause de non-réinstallation" in full
        assert "80 % des honoraires" in full
    if "texte-long" in filename:
        assert 'Анна / Ελένη' in normalized
        assert '250 €' in full
        for i in range(1, 36):
            assert f"Organisation détaillée {i} :" in full
    if "demande-etudiant" in filename:
        assert "ne valent pas autorisation" in full
    with pdfplumber.open(path) as pdf:
        for i, page in enumerate(pdf.pages, 1):
            chars = page.chars
            assert all(46 <= c["x0"] and c["x1"] <= page.width - 45 for c in chars), (filename, i, "Horizontal overflow")
            assert all(28 <= c["top"] and c["bottom"] < page.height - 30 for c in chars), (filename, i, "Vertical overflow")
            body = [c for c in chars if 70 <= c["top"] < page.height - 65]
            assert all(c["bottom"] < page.height - 68 for c in body), (filename, i, "Footer collision")
    print(f"{filename}: {page_count} pages, accents, contenu, signatures et marges OK")
